### PR TITLE
Added packet support for 1.13.1.

### PR DESCRIPTION
**Pull request by JabJabJab**

### CODE REVIEW

**Comment by Phoenix616** [comment]
Iirc it should not be necessary to register mappings for separate versions if the packet ID didn't change, Bungee should just use the next lowest packet automatically. Did you actually see issues when using it without that added mapping?

Also please follow the previous formatting of the file and only change lines that actually have programmatic changes. This  is a [really ugly diff](https://github.com/Phoenix616/ResourcepacksPlugins/pull/20/files?utf8=%E2%9C%93&diff=split).

**Comment by JabJabJab** [comment]
@Phoenix616 The formatting portion is my bad. I did this relatively quickly. The problem is your plug-in did not operate properly without this mapping. I received a bad packet error on logging into my server.

**Comment by Phoenix616** [comment]
Could you provide the error message that you've got?

**Comment by JabJabJab** [comment]
@Phoenix616 I have closed this pull request and created another one to respect your format.

**Pull request closed without merging**
